kind: pipeline
type: docker
name: default

steps:
  - name: print-message
    image: alpine:latest
    commands:
      - echo "Hello, Drone CI! This is a simple pipeline."
    - name: Next-message
    image: alpine:latest
    commands:
      - echo "Hi, This is my next pipeline test for my DRONE CI/CD pipeline. Many thanks".